kind: BuildConfig
apiVersion: v1
metadata:
  name: statustest-pipeline
  labels:
    app: statustest
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  source:
    git:
      ref: master
      uri: "https://github.com/AdamBien/statustest.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
      - name: SERVICE_URI
        value: http://statustest.airhacks.svc:8080      
